FROM mcneilco/tomcat-maven:openjdk8
WORKDIR /src
ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH
ADD 	pom.xml /src/pom.xml
RUN 	["mvn", "dependency:resolve", "-P indigo"]
RUN		["mvn", "clean"]
ADD		. /src
RUN		mvn compile war:war -P indigo
RUN		mv target/cmpdreg*.war $CATALINA_HOME/webapps/cmpdreg.war
RUN             mv target/*BUILD* $CATALINA_HOME/webapps/cmpdreg
RUN		rm -rf /src
WORKDIR	$CATALINA_HOME
EXPOSE	8080
CMD		["catalina.sh", "run"]
