// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.cmpdreg.dto;

import com.labsynch.cmpdreg.dto.MolInputDTO;

privileged aspect MolInputDTO_Roo_JavaBean {
    
    public String MolInputDTO.getStructure() {
        return this.structure;
    }
    
    public void MolInputDTO.setStructure(String structure) {
        this.structure = structure;
    }
    
}
