// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.cmpdreg.web;

import org.springframework.ui.Model;

import com.labsynch.cmpdreg.domain.Isotope;

privileged aspect IsotopeController_Roo_Controller {
    
    void IsotopeController.populateEditForm(Model uiModel, Isotope isotope) {
        uiModel.addAttribute("isotope", isotope);
    }
    
}
