// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.cmpdreg.web;

import com.labsynch.cmpdreg.web.SolutionUnitController;
import com.labsynch.cmpdreg.web.SolutionUnitController_Roo_Controller;
import com.labsynch.cmpdreg.web.SolutionUnitController_Roo_GvNIXDatatables;

privileged aspect SolutionUnitController_Roo_GvNIXDatatables {
    
    declare precedence: SolutionUnitController_Roo_GvNIXDatatables, SolutionUnitController_Roo_Controller;
    
}
