// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.cmpdreg.domain;

import com.labsynch.cmpdreg.domain.FileList;

privileged aspect FileList_Roo_JavaBean {
    
    public String FileList.getFilePath() {
        return this.filePath;
    }
    
    public void FileList.setFilePath(String filePath) {
        this.filePath = filePath;
    }
    
}
