// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.cmpdreg.domain;

import com.labsynch.cmpdreg.domain.SolutionUnit;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SolutionUnit_Roo_Configurable {
    
    declare @type: SolutionUnit: @Configurable;
    
}
