// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.cmpdreg.domain;

import com.labsynch.cmpdreg.domain.Salt;
import com.labsynch.cmpdreg.domain.SaltDataOnDemand;
import com.labsynch.cmpdreg.domain.SaltIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SaltIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SaltIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SaltIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SaltIntegrationTest: @Transactional;
    
    @Autowired
    SaltDataOnDemand SaltIntegrationTest.dod;
    
    @Test
    public void SaltIntegrationTest.testCountSalts() {
        Assert.assertNotNull("Data on demand for 'Salt' failed to initialize correctly", dod.getRandomSalt());
        long count = Salt.countSalts();
        Assert.assertTrue("Counter for 'Salt' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SaltIntegrationTest.testFindSalt() {
        Salt obj = dod.getRandomSalt();
        Assert.assertNotNull("Data on demand for 'Salt' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Salt' failed to provide an identifier", id);
        obj = Salt.findSalt(id);
        Assert.assertNotNull("Find method for 'Salt' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Salt' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SaltIntegrationTest.testFindAllSalts() {
        Assert.assertNotNull("Data on demand for 'Salt' failed to initialize correctly", dod.getRandomSalt());
        long count = Salt.countSalts();
        Assert.assertTrue("Too expensive to perform a find all test for 'Salt', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Salt> result = Salt.findAllSalts();
        Assert.assertNotNull("Find all method for 'Salt' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Salt' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SaltIntegrationTest.testFindSaltEntries() {
        Assert.assertNotNull("Data on demand for 'Salt' failed to initialize correctly", dod.getRandomSalt());
        long count = Salt.countSalts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Salt> result = Salt.findSaltEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Salt' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Salt' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SaltIntegrationTest.testFlush() {
        Salt obj = dod.getRandomSalt();
        Assert.assertNotNull("Data on demand for 'Salt' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Salt' failed to provide an identifier", id);
        obj = Salt.findSalt(id);
        Assert.assertNotNull("Find method for 'Salt' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySalt(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Salt' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SaltIntegrationTest.testMergeUpdate() {
        Salt obj = dod.getRandomSalt();
        Assert.assertNotNull("Data on demand for 'Salt' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Salt' failed to provide an identifier", id);
        obj = Salt.findSalt(id);
        boolean modified =  dod.modifySalt(obj);
        Integer currentVersion = obj.getVersion();
        Salt merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Salt' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SaltIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Salt' failed to initialize correctly", dod.getRandomSalt());
        Salt obj = dod.getNewTransientSalt(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Salt' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Salt' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Salt' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SaltIntegrationTest.testRemove() {
        Salt obj = dod.getRandomSalt();
        Assert.assertNotNull("Data on demand for 'Salt' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Salt' failed to provide an identifier", id);
        obj = Salt.findSalt(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Salt' with identifier '" + id + "'", Salt.findSalt(id));
    }
    
}
