// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.cmpdreg.domain;

import com.labsynch.cmpdreg.domain.SaltIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SaltIntegrationTest_Roo_Configurable {
    
    declare @type: SaltIntegrationTest: @Configurable;
    
}
