// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.cmpdreg.domain;

import com.labsynch.cmpdreg.domain.StandardizationSettings;
import com.labsynch.cmpdreg.domain.StandardizationSettingsDataOnDemand;
import com.labsynch.cmpdreg.domain.StandardizationSettingsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StandardizationSettingsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StandardizationSettingsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StandardizationSettingsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StandardizationSettingsIntegrationTest: @Transactional;
    
    @Autowired
    StandardizationSettingsDataOnDemand StandardizationSettingsIntegrationTest.dod;
    
    @Test
    public void StandardizationSettingsIntegrationTest.testCountStandardizationSettingses() {
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to initialize correctly", dod.getRandomStandardizationSettings());
        long count = StandardizationSettings.countStandardizationSettingses();
        Assert.assertTrue("Counter for 'StandardizationSettings' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StandardizationSettingsIntegrationTest.testFindStandardizationSettings() {
        StandardizationSettings obj = dod.getRandomStandardizationSettings();
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to provide an identifier", id);
        obj = StandardizationSettings.findStandardizationSettings(id);
        Assert.assertNotNull("Find method for 'StandardizationSettings' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StandardizationSettings' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StandardizationSettingsIntegrationTest.testFindAllStandardizationSettingses() {
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to initialize correctly", dod.getRandomStandardizationSettings());
        long count = StandardizationSettings.countStandardizationSettingses();
        Assert.assertTrue("Too expensive to perform a find all test for 'StandardizationSettings', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StandardizationSettings> result = StandardizationSettings.findAllStandardizationSettingses();
        Assert.assertNotNull("Find all method for 'StandardizationSettings' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StandardizationSettings' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StandardizationSettingsIntegrationTest.testFindStandardizationSettingsEntries() {
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to initialize correctly", dod.getRandomStandardizationSettings());
        long count = StandardizationSettings.countStandardizationSettingses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StandardizationSettings> result = StandardizationSettings.findStandardizationSettingsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StandardizationSettings' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StandardizationSettings' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StandardizationSettingsIntegrationTest.testFlush() {
        StandardizationSettings obj = dod.getRandomStandardizationSettings();
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to provide an identifier", id);
        obj = StandardizationSettings.findStandardizationSettings(id);
        Assert.assertNotNull("Find method for 'StandardizationSettings' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStandardizationSettings(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StandardizationSettings' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StandardizationSettingsIntegrationTest.testMergeUpdate() {
        StandardizationSettings obj = dod.getRandomStandardizationSettings();
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to provide an identifier", id);
        obj = StandardizationSettings.findStandardizationSettings(id);
        boolean modified =  dod.modifyStandardizationSettings(obj);
        Integer currentVersion = obj.getVersion();
        StandardizationSettings merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StandardizationSettings' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StandardizationSettingsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to initialize correctly", dod.getRandomStandardizationSettings());
        StandardizationSettings obj = dod.getNewTransientStandardizationSettings(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StandardizationSettings' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'StandardizationSettings' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StandardizationSettingsIntegrationTest.testRemove() {
        StandardizationSettings obj = dod.getRandomStandardizationSettings();
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StandardizationSettings' failed to provide an identifier", id);
        obj = StandardizationSettings.findStandardizationSettings(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StandardizationSettings' with identifier '" + id + "'", StandardizationSettings.findStandardizationSettings(id));
    }
    
}
